NODE_NAME = "firos"

SERVER = {
    "ADDRESS" : "0.0.0.0",
    "PORT"    : 10100
}

# Context type constants

CONTEXTBROKER = {
    "ADDRESS" : "130.206.127.115",
    "PORT"    : 1026,
    "PROTOCOL": "NGSI10"
}

DEFAULT_CONTEXT_TYPE = "ROBOT"
DEFAULT_QUEUE_SIZE = 10

# THROTTLING = "PT1S"
THROTTLING = "PT0S"
